Gleyce Andrade Silva - RA:818125665 Lucas Alves Xavier - RA: 818121050 Lucas Amaral - RA:818115153 Mayara Andrade Silva - RA:818146535


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from google.colab import files
uploaded = files.upload()

Saving basecensus.csv.xlsx to basecensus.csv.xlsx


In [3]:
df = pd.read_excel('basecensus.csv.xlsx')

In [4]:
df.columns

Index(['Unnamed: 0', 'age', 'workclass', 'final.weight', 'education',
       'education.num', 'marital.status', 'occupation', 'relationship', 'race',
       'sex', 'capital.gain', 'capital.loos', 'hour.per.week',
       'native.country', 'income'],
      dtype='object')

In [5]:
print(df.dtypes)

Unnamed: 0         int64
age                int64
workclass         object
final.weight       int64
education         object
education.num      int64
marital.status    object
occupation        object
relationship      object
race              object
sex               object
capital.gain       int64
capital.loos       int64
hour.per.week      int64
native.country    object
income            object
dtype: object


In [6]:
df.head()

Unnamed: 0  age          workclass  ...  hour.per.week  native.country  income
0           1   39          State-gov  ...             40   United-States   <=50K
1           2   50   Self-emp-not-inc  ...             13   United-States   <=50K
2           3   38            Private  ...             40   United-States   <=50K
3           4   53            Private  ...             40   United-States   <=50K
4           5   28            Private  ...             40            Cuba   <=50K

[5 rows x 16 columns]

In [7]:
df.columns

Index(['Unnamed: 0', 'age', 'workclass', 'final.weight', 'education',
       'education.num', 'marital.status', 'occupation', 'relationship', 'race',
       'sex', 'capital.gain', 'capital.loos', 'hour.per.week',
       'native.country', 'income'],
      dtype='object')

In [8]:
df.isnull().sum()

Unnamed: 0        0
age               0
workclass         0
final.weight      0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loos      0
hour.per.week     0
native.country    0
income            0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30162 entries, 0 to 30161
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      30162 non-null  int64 
 1   age             30162 non-null  int64 
 2   workclass       30162 non-null  object
 3   final.weight    30162 non-null  int64 
 4   education       30162 non-null  object
 5   education.num   30162 non-null  int64 
 6   marital.status  30162 non-null  object
 7   occupation      30162 non-null  object
 8   relationship    30162 non-null  object
 9   race            30162 non-null  object
 10  sex             30162 non-null  object
 11  capital.gain    30162 non-null  int64 
 12  capital.loos    30162 non-null  int64 
 13  hour.per.week   30162 non-null  int64 
 14  native.country  30162 non-null  object
 15  income          30162 non-null  object
dtypes: int64(7), object(9)
memory usage: 3.7+ MB


In [10]:
filtro  = df['education'].__eq__(' HS-grad')
df1 = df[filtro]

filtro  = df['education'].__eq__(' Some-college')
df2 = df[filtro]

filtro  = df['education'].__eq__(' Bachelors')
df3 = df[filtro]


finalDf = pd.concat([df1, df2, df3])

In [11]:
finalDf = finalDf[(finalDf.astype(str) != ' ?').all(axis=1)]
len(finalDf) # 30162

21562

In [ ]:
finalDf.head()

Unnamed: 0  age          workclass  ...  hour.per.week  native.country  income
2            3   38            Private  ...             40   United-States   <=50K
7            8   52   Self-emp-not-inc  ...             45   United-States    >50K
15          17   25   Self-emp-not-inc  ...             35   United-States   <=50K
16          18   32            Private  ...             40   United-States   <=50K
20          22   54            Private  ...             20   United-States   <=50K

[5 rows x 16 columns]

In [ ]:
finalDf['education'].value_counts()

 HS-grad         9840
 Some-college    6678
 Bachelors       5044
 11th            1048
Name: education, dtype: int64

In [12]:
finalDf['income_bi'] = finalDf.apply(lambda row: 1 if '>50K'in row['income'] else 0, axis=1)

In [13]:
finalDf = finalDf.drop(['income','capital.gain','capital.loos','Unnamed: 0','education.num','age','workclass','final.weight','marital.status'], axis=1)

In [14]:
finalDf = pd.get_dummies(finalDf, columns=['occupation','relationship','sex','native.country','race'])

In [15]:
finalDf.head()

education  hour.per.week  income_bi  ...  race_ Black  race_ Other  race_ White
2    HS-grad             40          0  ...            0            0            1
7    HS-grad             45          1  ...            0            0            1
15   HS-grad             35          0  ...            0            0            1
16   HS-grad             40          0  ...            0            0            1
20   HS-grad             20          0  ...            1            0            0

[5 rows x 71 columns]

In [ ]:
finalDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22610 entries, 2 to 30129
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   age          22610 non-null  int64 
 1   education    22610 non-null  object
 2   income_bi    22610 non-null  int64 
 3   Nsex         22610 non-null  int64 
 4   Nrace        22610 non-null  int64 
 5   Nmarital     22610 non-null  int64 
 6   Nrelat       22610 non-null  int64 
 7   Ncountry     22610 non-null  int64 
 8   Nwork        22610 non-null  int64 
 9   Noccupation  22610 non-null  int64 
dtypes: int64(9), object(1)
memory usage: 1.9+ MB


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(finalDf.drop('education',axis=1), finalDf['education'], test_size=0.90, random_state=101)
X_train
y_test

16092          HS-grad
303       Some-college
1175           HS-grad
15964          HS-grad
18978          HS-grad
             ...      
24677          HS-grad
16991     Some-college
3619           HS-grad
7363           HS-grad
2050         Bachelors
Name: education, Length: 19406, dtype: object

In [20]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(solver='lbfgs',max_iter=5000)
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)

In [21]:
predictions = logmodel.predict(X_test)
predictions

array([' HS-grad', ' Bachelors', ' HS-grad', ..., ' HS-grad',
       ' Bachelors', ' Bachelors'], dtype=object)

In [22]:
import pandas as pd

print("\nMatriz de confusão detalhada:\n",
      pd.crosstab(y_test, predictions, rownames=['Real'], colnames=['Predito'],
      margins=True, margins_name='Todos'))


Matriz de confusão detalhada:
 Predito         Bachelors   HS-grad   Some-college  Todos
Real                                                     
 Bachelors           2819      1245            440   4504
 HS-grad              971      7052            845   8868
 Some-college        1241      3707           1086   6034
Todos                5031     12004           2371  19406


In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

               precision    recall  f1-score   support

    Bachelors       0.56      0.63      0.59      4504
      HS-grad       0.59      0.80      0.68      8868
 Some-college       0.46      0.18      0.26      6034

     accuracy                           0.56     19406
    macro avg       0.54      0.53      0.51     19406
 weighted avg       0.54      0.56      0.53     19406



In [25]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, predictions)
print(conf_mat)

[[2819 1245  440]
 [ 971 7052  845]
 [1241 3707 1086]]


In [26]:
predito = logmodel.predict([[40,	1,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	1]]) 
print(predito)

[' Bachelors']
